In [3]:
import numpy as np
import pandas as pd

index = pd.date_range('1/1/2000', periods=8)
s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
df = pd.DataFrame(np.random.randn(8, 3), index=index,
                    columns=['A', 'B', 'C'])

In [2]:
# Head and tail

long_series = pd.Series(np.random.randn(1000))
long_series.head()

0    0.447984
1   -0.115637
2    0.207955
3   -2.333673
4    1.934435
dtype: float64

In [9]:
long_series.tail(3)

997   -0.320646
998    0.311030
999   -0.385003
dtype: float64

In [40]:
# Attributes and underlying data

df[:2]

one       two     three
a  0.383948 -0.518727       NaN
b  0.176186 -0.375242  0.590151

In [6]:
df.columns = [x.lower() for x in df.columns]
df

a         b         c
2000-01-01  0.349640 -0.350734 -0.429591
2000-01-02  1.416604  0.970359  1.786589
2000-01-03 -0.838714 -2.002942 -0.135257
2000-01-04 -0.318140 -1.530065  0.598659
2000-01-05 -1.094929  0.734259 -0.106070
2000-01-06 -1.045515  0.546486 -0.446712
2000-01-07 -1.710531 -1.099789 -1.078487
2000-01-08  0.940102  0.296735 -1.055584

In [7]:
s.array

<PandasArray>
[ -0.502565320456717,  1.3693081083831367, -1.3344818397436358,
  0.5211512757240769, -0.7249872470227884]
Length: 5, dtype: float64

In [8]:
s.index.array

<PandasArray>
['a', 'b', 'c', 'd', 'e']
Length: 5, dtype: object

In [9]:
s.to_numpy()

array([-0.50256532,  1.36930811, -1.33448184,  0.52115128, -0.72498725])

In [10]:
np.asarray(s)

array([-0.50256532,  1.36930811, -1.33448184,  0.52115128, -0.72498725])

In [11]:
ser = pd.Series(pd.date_range('2000', periods=2, tz="CET"))
ser.to_numpy(dtype=object)

array([Timestamp('2000-01-01 00:00:00+0100', tz='CET', freq='D'),
       Timestamp('2000-01-02 00:00:00+0100', tz='CET', freq='D')],
      dtype=object)

In [12]:
ser.to_numpy(dtype="datetime64[ns]")

array(['1999-12-31T23:00:00.000000000', '2000-01-01T23:00:00.000000000'],
      dtype='datetime64[ns]')

In [13]:
df.to_numpy()

array([[ 0.34964027, -0.35073376, -0.42959052],
       [ 1.41660388,  0.97035942,  1.78658921],
       [-0.83871437, -2.00294236, -0.13525711],
       [-0.31813952, -1.53006486,  0.59865866],
       [-1.09492901,  0.73425925, -0.10606991],
       [-1.04551501,  0.54648599, -0.44671174],
       [-1.71053068, -1.09978907, -1.07848653],
       [ 0.94010202,  0.29673505, -1.05558432]])

In [14]:
# Accelerated operations

pd.set_option('compute.use_bottleneck', False)
pd.set_option('compute.use_numexpr', False)

In [15]:
# Flexible binary operations

df = pd.DataFrame({
    'one': pd.Series(np.random.randn(3), index=['a', 'b', 'c']),
    'two': pd.Series(np.random.randn(4), index=['a', 'b', 'c', 'd']),
    'three': pd.Series(np.random.randn(3), index=['b', 'c', 'd'])})
df

one       two     three
a  0.383948 -0.518727       NaN
b  0.176186 -0.375242  0.590151
c -2.641514  0.494866 -0.479331
d       NaN  2.445402 -0.689410

In [16]:
row = df.iloc[1]
column = df['two']
df.sub(row, axis='columns')

one       two     three
a  0.207762 -0.143485       NaN
b  0.000000  0.000000  0.000000
c -2.817700  0.870109 -1.069482
d       NaN  2.820644 -1.279562

In [17]:
df.sub(row, axis=1)

one       two     three
a  0.207762 -0.143485       NaN
b  0.000000  0.000000  0.000000
c -2.817700  0.870109 -1.069482
d       NaN  2.820644 -1.279562

In [18]:
df.sub(column, axis='index')

one  two     three
a  0.902675  0.0       NaN
b  0.551428  0.0  0.965394
c -3.136380  0.0 -0.974197
d       NaN  0.0 -3.134812

In [19]:
df.sub(column, axis=0)

one  two     three
a  0.902675  0.0       NaN
b  0.551428  0.0  0.965394
c -3.136380  0.0 -0.974197
d       NaN  0.0 -3.134812

In [20]:
dfmi = df.copy()
dfmi.index = pd.MultiIndex.from_tuples([(1, 'a'), (1, 'b'),
                                        (1, 'c'), (2, 'a')],
                                        names=['first', 'second'])
dfmi.sub(column, axis=0, level='second')

one       two     three
first second                              
1     a       0.902675  0.000000       NaN
      b       0.551428  0.000000  0.965394
      c      -3.136380  0.000000 -0.974197
2     a            NaN  2.964129 -0.170683

In [23]:
s = pd.Series(np.arange(10))
s

0    0
1    1
2    2
3    3
4    4
5    5
6    6
7    7
8    8
9    9
dtype: int32

In [24]:
div, rem = divmod(s, 3)
div

0    0
1    0
2    0
3    1
4    1
5    1
6    2
7    2
8    2
9    3
dtype: int32

In [25]:
rem

0    0
1    1
2    2
3    0
4    1
5    2
6    0
7    1
8    2
9    0
dtype: int32

In [26]:
idx = pd.Index(np.arange(10))
idx

Int64Index([0, 1, 2, 3, 4, 5, 6, 7, 8, 9], dtype='int64')

In [28]:
div, rem = divmod(idx, 3)
div

Int64Index([0, 0, 0, 1, 1, 1, 2, 2, 2, 3], dtype='int64')

In [29]:
rem

Int64Index([0, 1, 2, 0, 1, 2, 0, 1, 2, 0], dtype='int64')

In [30]:
div, rem = divmod(s, [2, 2, 3, 3, 4, 4, 5, 5, 6, 6])
div

0    0
1    0
2    0
3    1
4    1
5    1
6    1
7    1
8    1
9    1
dtype: int32

In [31]:
rem

0    0
1    1
2    2
3    0
4    0
5    1
6    1
7    2
8    2
9    3
dtype: int32

In [32]:
# Missing data / operations with fill values

df

one       two     three
a  0.383948 -0.518727       NaN
b  0.176186 -0.375242  0.590151
c -2.641514  0.494866 -0.479331
d       NaN  2.445402 -0.689410

In [38]:
df[:2]

one       two     three
a  0.383948 -0.518727       NaN
b  0.176186 -0.375242  0.590151

In [37]:
df + df[:2]

one       two     three
a  0.767895 -1.037454       NaN
b  0.352372 -0.750485  1.180302
c       NaN       NaN       NaN
d       NaN       NaN       NaN

In [36]:
df.add(df[:2], fill_value=0)

one       two     three
a  0.767895 -1.037454       NaN
b  0.352372 -0.750485  1.180302
c -2.641514  0.494866 -0.479331
d       NaN  2.445402 -0.689410

In [42]:
# Flexible comparisons

df.gt(df[:2])

one    two  three
a  False  False  False
b  False  False  False
c  False  False  False
d  False  False  False

In [43]:
df[:2].ne(df)

one    two  three
a  False  False   True
b  False  False  False
c   True   True   True
d   True   True   True

In [44]:
# Boolean reductions

(df > 0).all()

one      False
two      False
three    False
dtype: bool

In [45]:
(df > 0).any()

one      True
two      True
three    True
dtype: bool

In [46]:
(df > 0).any().any()

True

In [47]:
df.empty

False

In [48]:
pd.DataFrame(columns=list('ABC')).empty

True

In [49]:
pd.Series([True]).bool()

True

In [50]:
pd.Series([False]).bool()

False

In [51]:
pd.DataFrame([[True]]).bool()

True

In [52]:
pd.DataFrame([[False]]).bool()

False

In [54]:
# Comparing if objects are equivalent

df + df == df * 2

one   two  three
a   True  True  False
b   True  True   True
c   True  True   True
d  False  True   True

In [55]:
(df + df == df * 2).all()

one      False
two       True
three    False
dtype: bool

In [56]:
np.nan == np.nan

False

In [57]:
(df + df).equals(df * 2)

True

In [58]:
df1 = pd.DataFrame({'col': ['foo', 0, np.nan]})
df2 = pd.DataFrame({'col': [np.nan, 0, 'foo']}, index=[2, 1, 0])
df1.equals(df2)

False

In [59]:
df1.equals(df2.sort_index())

True

In [60]:
# Comparing array-like objects

pd.Series(['foo', 'bar', 'baz']) == 'foo'

0     True
1    False
2    False
dtype: bool

In [61]:
pd.Index(['foo', 'bar', 'baz']) == 'foo'

array([ True, False, False])

In [62]:
pd.Series(['foo', 'bar', 'baz']) == pd.Index(['foo', 'bar', 'qux'])

0     True
1     True
2    False
dtype: bool

In [63]:
pd.Series(['foo', 'bar', 'baz']) == np.array(['foo', 'bar', 'qux'])

0     True
1     True
2    False
dtype: bool

In [65]:
np.array([1, 2, 3]) == np.array([2])

array([False,  True, False])

In [66]:
np.array([1, 2, 3]) == np.array([1, 2])

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  """Entry point for launching an IPython kernel.


False

In [67]:
# Combining overlapping data sets

df1 = pd.DataFrame({'A': [1., np.nan, 3., 5., np.nan],
                    'B': [np.nan, 2., 3., np.nan, 6.]})
df2 = pd.DataFrame({'A': [5., 2., 4., np.nan, 3., 7.],
                    'B': [np.nan, np.nan, 3., 4., 6., 8.]})
df1

A    B
0  1.0  NaN
1  NaN  2.0
2  3.0  3.0
3  5.0  NaN
4  NaN  6.0

In [68]:
df2

A    B
0  5.0  NaN
1  2.0  NaN
2  4.0  3.0
3  NaN  4.0
4  3.0  6.0
5  7.0  8.0

In [69]:
df1.combine_first(df2)

A    B
0  1.0  NaN
1  2.0  2.0
2  3.0  3.0
3  5.0  4.0
4  3.0  6.0
5  7.0  8.0

In [70]:
# General DataFrame combine

def combiner(x, y):
    return np.where(pd.isna(x), y, x)

In [72]:
# Descriptive statistics

df

one       two     three
a  0.383948 -0.518727       NaN
b  0.176186 -0.375242  0.590151
c -2.641514  0.494866 -0.479331
d       NaN  2.445402 -0.689410

In [73]:
df.mean(0)

one     -0.693794
two      0.511575
three   -0.192863
dtype: float64

In [74]:
df.mean(1)

a   -0.067390
b    0.130365
c   -0.875326
d    0.877996
dtype: float64

In [75]:
df.sum(0, skipna=False)

one           NaN
two      2.046298
three         NaN
dtype: float64

In [76]:
df.sum(axis=1, skipna=True)

a   -0.134780
b    0.391095
c   -2.625979
d    1.755991
dtype: float64

In [77]:
ts_stand = (df - df.mean()) / df.std()
ts_stand.std()

one      1.0
two      1.0
three    1.0
dtype: float64

In [78]:
xs_stand = df.sub(df.mean(1), axis=0).div(df.std(1), axis=0)
xs_stand.std(1)

a    1.0
b    1.0
c    1.0
d    1.0
dtype: float64

In [79]:
df.cumsum()

one       two     three
a  0.383948 -0.518727       NaN
b  0.560134 -0.893970  0.590151
c -2.081381 -0.399103  0.110820
d       NaN  2.046298 -0.578590

In [80]:
np.mean(df['one'])

-0.6937935090609493

In [81]:
np.mean(df['one'].to_numpy())

nan

In [82]:
series = pd.Series(np.random.randn(500))
series[20:500] = np.nan
series[10:20] = 5
series.nunique()

11

In [83]:
# Summarizing data: describe

series = pd.Series(np.random.randn(1000))
series[::2] = np.nan
series.describe()

count    500.000000
mean       0.054669
std        1.028459
min       -3.203472
25%       -0.630041
50%       -0.009296
75%        0.718761
max        3.279050
dtype: float64

In [88]:
frame = pd.DataFrame(np.random.randn(1000, 5),
                    columns=['a', 'b', 'c', 'd', 'e'])
frame.iloc[::2] = np.nan
frame.describe()

a           b           c           d           e
count  500.000000  500.000000  500.000000  500.000000  500.000000
mean     0.028616   -0.031082   -0.087044   -0.076919   -0.019451
std      0.969590    1.018310    1.039562    0.975420    0.962543
min     -3.171708   -2.925592   -2.848862   -2.693899   -3.488695
25%     -0.625684   -0.721301   -0.814456   -0.694626   -0.682290
50%      0.065351   -0.023425   -0.066393   -0.035768   -0.018471
75%      0.689264    0.666250    0.658444    0.547005    0.614986
max      3.103583    2.618767    3.283568    3.130874    2.921414

In [89]:
series.describe(percentiles=[.05, .25, .75, .95])

count    500.000000
mean       0.054669
std        1.028459
min       -3.203472
5%        -1.579856
25%       -0.630041
50%       -0.009296
75%        0.718761
95%        1.836563
max        3.279050
dtype: float64

In [90]:
s = pd.Series(['a', 'a', 'b', 'b', 'a', 'a', np.nan, 'c', 'd', 'a'])
s.describe()

count     9
unique    4
top       a
freq      5
dtype: object

In [91]:
frame = pd.DataFrame({'a': ['Yes', 'Yes', 'No', 'No'], 'b': range(4)})
frame.describe()

b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

In [92]:
frame.describe(include=['object'])

a
count    4
unique   2
top     No
freq     2

In [93]:
frame.describe(include=['number'])

b
count  4.000000
mean   1.500000
std    1.290994
min    0.000000
25%    0.750000
50%    1.500000
75%    2.250000
max    3.000000

In [94]:
frame.describe(include='all')

a         b
count     4  4.000000
unique    2       NaN
top      No       NaN
freq      2       NaN
mean    NaN  1.500000
std     NaN  1.290994
min     NaN  0.000000
25%     NaN  0.750000
50%     NaN  1.500000
75%     NaN  2.250000
max     NaN  3.000000

In [95]:
# Index of min/max values

s1 = pd.Series(np.random.randn(5))
s1

0    1.534981
1   -0.554238
2    1.010964
3   -1.003935
4    0.064472
dtype: float64

In [96]:
s1.idxmin(), s1.idxmax()

(3, 0)

In [97]:
df1 = pd.DataFrame(np.random.randn(5, 3), columns=['A', 'B', 'C'])
df1

A         B         C
0 -0.078449 -1.655414 -2.612092
1  0.947047  2.506748  1.668440
2 -0.690613 -1.504070  0.386850
3 -0.840042 -1.126701 -0.861874
4  0.473736 -0.493150 -0.499044

In [98]:
df1.idxmin(axis=0)

A    3
B    0
C    0
dtype: int64

In [99]:
df1.idxmax(axis=1)

0    A
1    B
2    C
3    A
4    A
dtype: object

In [100]:
df3 = pd.DataFrame([2, 1, 1, 3, np.nan], columns=['A'], index=list('edcba'))
df3

A
e  2.0
d  1.0
c  1.0
b  3.0
a  NaN

In [102]:
df3['A'].idxmin()
                        # Note: idxmin and idxmax are called argmin and argmax in NumPy.


'd'

In [103]:
# Value counts (histogramming) / mode

data = np.random.randint(0, 7, size=50)
data

array([4, 5, 3, 5, 6, 6, 4, 0, 3, 6, 2, 2, 2, 0, 6, 6, 2, 4, 4, 3, 0, 3,
       6, 1, 5, 2, 6, 4, 2, 2, 0, 3, 6, 6, 3, 3, 3, 3, 4, 6, 1, 4, 6, 3,
       0, 2, 4, 4, 5, 1])

In [104]:
s = pd.Series(data)
s.value_counts()

6    11
3    10
4     9
2     8
0     5
5     4
1     3
dtype: int64

In [105]:
pd.value_counts(data)

6    11
3    10
4     9
2     8
0     5
5     4
1     3
dtype: int64

In [106]:
s5 = pd.Series([1, 1, 3, 3, 3, 5, 5, 7, 7, 7])
s5.mode()

0    3
1    7
dtype: int64

In [107]:
df5 = pd.DataFrame({"A": np.random.randint(0, 7, size=50),
                    "B": np.random.randint(-10, 15, size=50)})
df5.mode()

A   B
0  0.0  -4
1  NaN  13

In [108]:
# Discretization and quantiling

arr = np.random.randn(20)
factor = pd.cut(arr, 4)
factor

[(0.322, 1.267], (0.322, 1.267], (-0.624, 0.322], (0.322, 1.267], (-0.624, 0.322], ..., (0.322, 1.267], (-0.624, 0.322], (-1.573, -0.624], (-0.624, 0.322], (-0.624, 0.322]]
Length: 20
Categories (4, interval[float64]): [(-1.573, -0.624] < (-0.624, 0.322] < (0.322, 1.267] < (1.267, 2.213]]

In [109]:
factor = pd.cut(arr, [-5, -1, 0, 1, 5])
factor

[(0, 1], (1, 5], (-1, 0], (0, 1], (-1, 0], ..., (0, 1], (-1, 0], (-5, -1], (-1, 0], (0, 1]]
Length: 20
Categories (4, interval[int64]): [(-5, -1] < (-1, 0] < (0, 1] < (1, 5]]

In [110]:
arr = np.random.randn(30)
factor = pd.qcut(arr, [0, .25, .5, .75, 1])
factor

[(-1.5219999999999998, -0.627], (-1.5219999999999998, -0.627], (-0.627, -0.027], (-0.027, 0.362], (-0.027, 0.362], ..., (0.362, 1.703], (-0.027, 0.362], (-1.5219999999999998, -0.627], (-0.027, 0.362], (0.362, 1.703]]
Length: 30
Categories (4, interval[float64]): [(-1.5219999999999998, -0.627] < (-0.627, -0.027] < (-0.027, 0.362] < (0.362, 1.703]]

In [111]:
pd.value_counts(factor)

(0.362, 1.703]                   8
(-1.5219999999999998, -0.627]    8
(-0.027, 0.362]                  7
(-0.627, -0.027]                 7
dtype: int64

In [112]:
arr = np.random.randn(20)
factor = pd.cut(arr, [-np.inf, 0, np.inf])
factor

[(-inf, 0.0], (-inf, 0.0], (-inf, 0.0], (-inf, 0.0], (0.0, inf], ..., (-inf, 0.0], (-inf, 0.0], (-inf, 0.0], (-inf, 0.0], (-inf, 0.0]]
Length: 20
Categories (2, interval[float64]): [(-inf, 0.0] < (0.0, inf]]

In [121]:
# Function application
# Tablewise function application



NameError: name 'f' is not defined

In [124]:
import statsmodels.formula.api as sm
bb = pd.read_csv('data/baseball.csv', index_col='id')
(bb.query('h > 0')
    .assign(ln_h=lambda df: np.log(df.h))
    .pipe((sm.ols, 'data'), 'hr ~ ln_h + year + g + C(lg)')
    .fit()
    .summary()
)

FileNotFoundError: [Errno 2] File b'data/baseball.csv' does not exist: b'data/baseball.csv'

In [126]:
# Row or column-wise function application

df.apply(np.mean)

one     -0.693794
two      0.511575
three   -0.192863
dtype: float64

In [127]:
df.apply(np.mean, axis=1)

a   -0.067390
b    0.130365
c   -0.875326
d    0.877996
dtype: float64

In [128]:
df.apply(lambda x: x.max() - x.min())

one      3.025462
two      2.964129
three    1.279562
dtype: float64

In [129]:
df.apply(np.cumsum)

one       two     three
a  0.383948 -0.518727       NaN
b  0.560134 -0.893970  0.590151
c -2.081381 -0.399103  0.110820
d       NaN  2.046298 -0.578590

In [130]:
df.apply(np.exp)

one        two     three
a  1.468068   0.595278       NaN
b  1.192660   0.687123  1.804261
c  0.071253   1.640279  0.619198
d       NaN  11.535183  0.501872

In [131]:
df.apply('mean')

one     -0.693794
two      0.511575
three   -0.192863
dtype: float64

In [132]:
df.apply('mean', axis=1)

a   -0.067390
b    0.130365
c   -0.875326
d    0.877996
dtype: float64

In [136]:
tsdf = pd.DataFrame(np.random.randn(1000, 3), columns=['A', 'B', 'C'],
                    index=pd.date_range('1/1/2000', periods=1000))
tsdf.apply(lambda x: x.idxmax())

A   2001-10-05
B   2001-11-28
C   2001-08-06
dtype: datetime64[ns]

In [140]:
def subtract_and_divide(x, sub, divide=1):
    return (x - sub) / divide

In [141]:
df.apply(subtract_and_divide, args=(5,), divide=3)

one       two     three
a -1.538684 -1.839576       NaN
b -1.607938 -1.791747 -1.469950
c -2.547171 -1.501711 -1.826444
d       NaN -0.851533 -1.896470

In [142]:
tsdf

A         B         C
2000-01-01  0.184189 -1.929472 -0.249695
2000-01-02 -0.045723 -1.906964  0.658548
2000-01-03  0.619075 -1.957448  0.142987
2000-01-04 -0.330763 -1.720047 -0.294513
2000-01-05 -0.558134  1.071653 -0.340656
2000-01-06  0.086935  0.151674  0.521209
2000-01-07 -1.172979  1.960659  0.267750
2000-01-08 -2.299794  0.375621  1.525917
2000-01-09  1.145541 -0.270732 -0.643302
2000-01-10  0.126422 -0.784183  0.411622
2000-01-11 -0.291046 -0.758683  0.646626
2000-01-12  0.840859  0.820592  1.033203
2000-01-13 -0.168408 -0.658156  0.994279
2000-01-14  1.240310  1.238352 -1.276806
2000-01-15 -0.836528 -0.664286  0.345912
2000-01-16  0.735862  0.203409 -0.899328
2000-01-17 -0.493171  2.068789  0.343190
2000-01-18  0.490171  0.827664 -0.223174
2000-01-19 -1.012205 -1.067437  0.366822
2000-01-20 -0.064192  1.696620  1.837332
2000-01-21  0.866694  1.646801  0.222986
2000-01-22 -1.693228 -0.440249 -1.437997
2000-01-23  1.127546 -0.443936 -1.304903
2000-01-24  0.389823 -1.589064 -1.076044
2000-01-25 -0.633589  0.880528  0.523618
2000-01-26  0.911930  0.296280  0.881748
2000-01-27  2.139684  0.444219  1.109756
2000-01-28 -0.726456 -0.078613  0.275450
2000-01-29 -0.899345  0.465126  0.811624
2000-01-30 -1.811902 -0.202571  1.250266
...              ...       ...       ...
2002-08-28 -0.042626 -1.554821 -1.831413
2002-08-29 -0.014028 -0.710025  0.006301
2002-08-30 -0.409779 -1.248836 -1.052548
2002-08-31  0.550815  1.877631 -0.355613
2002-09-01 -0.403448  0.156628 -0.393208
2002-09-02 -0.637835  0.781567  0.495174
2002-09-03 -1.056955 -0.010385 -1.690648
2002-09-04 -0.177935 -0.597268  1.465331
2002-09-05 -0.381687  0.881906  0.042880
2002-09-06  2.122290 -1.285917 -0.782623
2002-09-07 -0.305130  1.013412  0.376164
2002-09-08 -1.145871  0.068578  1.817724
2002-09-09  0.467509 -0.531617 -0.942727
2002-09-10  2.210201 -2.797159  0.888783
2002-09-11  0.669878 -1.095200  1.703499
2002-09-12  0.052304  0.328665 -1.078154
2002-09-13 -0.872263  0.711065  0.706604
2002-09-14  0.978742  0.946234  1.604117
2002-09-15  1.358512  0.923487  1.194100
2002-09-16  0.579116  0.242302 -1.799006
2002-09-17  1.333887  0.714383 -1.548916
2002-09-18  0.060176 -0.159796 -0.404422
2002-09-19 -0.487591 -0.407015 -0.278354
2002-09-20  0.615058 -2.682870  0.496790
2002-09-21 -0.335104  1.487716  0.609615
2002-09-22 -1.146274  1.278606  0.328343
2002-09-23  0.282469  0.437969 -0.242239
2002-09-24 -1.236301 -1.799501 -0.344370
2002-09-25  0.544096  0.700691 -0.410487
2002-09-26 -0.254930 -0.013325 -0.722671

[1000 rows x 3 columns]

In [143]:
tsdf.apply(pd.Series.interpolate)

A         B         C
2000-01-01  0.184189 -1.929472 -0.249695
2000-01-02 -0.045723 -1.906964  0.658548
2000-01-03  0.619075 -1.957448  0.142987
2000-01-04 -0.330763 -1.720047 -0.294513
2000-01-05 -0.558134  1.071653 -0.340656
2000-01-06  0.086935  0.151674  0.521209
2000-01-07 -1.172979  1.960659  0.267750
2000-01-08 -2.299794  0.375621  1.525917
2000-01-09  1.145541 -0.270732 -0.643302
2000-01-10  0.126422 -0.784183  0.411622
2000-01-11 -0.291046 -0.758683  0.646626
2000-01-12  0.840859  0.820592  1.033203
2000-01-13 -0.168408 -0.658156  0.994279
2000-01-14  1.240310  1.238352 -1.276806
2000-01-15 -0.836528 -0.664286  0.345912
2000-01-16  0.735862  0.203409 -0.899328
2000-01-17 -0.493171  2.068789  0.343190
2000-01-18  0.490171  0.827664 -0.223174
2000-01-19 -1.012205 -1.067437  0.366822
2000-01-20 -0.064192  1.696620  1.837332
2000-01-21  0.866694  1.646801  0.222986
2000-01-22 -1.693228 -0.440249 -1.437997
2000-01-23  1.127546 -0.443936 -1.304903
2000-01-24  0.389823 -1.589064 -1.076044
2000-01-25 -0.633589  0.880528  0.523618
2000-01-26  0.911930  0.296280  0.881748
2000-01-27  2.139684  0.444219  1.109756
2000-01-28 -0.726456 -0.078613  0.275450
2000-01-29 -0.899345  0.465126  0.811624
2000-01-30 -1.811902 -0.202571  1.250266
...              ...       ...       ...
2002-08-28 -0.042626 -1.554821 -1.831413
2002-08-29 -0.014028 -0.710025  0.006301
2002-08-30 -0.409779 -1.248836 -1.052548
2002-08-31  0.550815  1.877631 -0.355613
2002-09-01 -0.403448  0.156628 -0.393208
2002-09-02 -0.637835  0.781567  0.495174
2002-09-03 -1.056955 -0.010385 -1.690648
2002-09-04 -0.177935 -0.597268  1.465331
2002-09-05 -0.381687  0.881906  0.042880
2002-09-06  2.122290 -1.285917 -0.782623
2002-09-07 -0.305130  1.013412  0.376164
2002-09-08 -1.145871  0.068578  1.817724
2002-09-09  0.467509 -0.531617 -0.942727
2002-09-10  2.210201 -2.797159  0.888783
2002-09-11  0.669878 -1.095200  1.703499
2002-09-12  0.052304  0.328665 -1.078154
2002-09-13 -0.872263  0.711065  0.706604
2002-09-14  0.978742  0.946234  1.604117
2002-09-15  1.358512  0.923487  1.194100
2002-09-16  0.579116  0.242302 -1.799006
2002-09-17  1.333887  0.714383 -1.548916
2002-09-18  0.060176 -0.159796 -0.404422
2002-09-19 -0.487591 -0.407015 -0.278354
2002-09-20  0.615058 -2.682870  0.496790
2002-09-21 -0.335104  1.487716  0.609615
2002-09-22 -1.146274  1.278606  0.328343
2002-09-23  0.282469  0.437969 -0.242239
2002-09-24 -1.236301 -1.799501 -0.344370
2002-09-25  0.544096  0.700691 -0.410487
2002-09-26 -0.254930 -0.013325 -0.722671

[1000 rows x 3 columns]

In [144]:
# Aggregation API

tsdf = pd.DataFrame(np.random.randn(10, 3), columns=['A', 'B', 'C'],
                    index=pd.date_range('1/1/2000', periods=10))
tsdf.iloc[3:7] = np.nan
tsdf

A         B         C
2000-01-01 -1.060387  0.376429 -0.344146
2000-01-02  0.589233  0.298249  0.389040
2000-01-03  0.577302 -1.487722  3.036243
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08 -2.453917 -1.456879 -0.961287
2000-01-09 -0.753730 -0.452103 -0.378489
2000-01-10  1.011114 -1.257591 -2.325686

In [145]:
tsdf.agg(np.sum)

A   -2.090386
B   -3.979617
C   -0.584324
dtype: float64

In [146]:
tsdf.agg('sum')

A   -2.090386
B   -3.979617
C   -0.584324
dtype: float64

In [147]:
#these are equivalent to a ``.sum()`` because we are aggregating
# on a single function
tsdf.sum()

A   -2.090386
B   -3.979617
C   -0.584324
dtype: float64

In [148]:
tsdf.A.agg('sum')

-2.090385728173305

In [151]:
tsdf.agg(['sum'])

A         B         C
sum -2.090386 -3.979617 -0.584324

In [152]:
tsdf.agg(['sum', 'mean'])

A         B         C
sum  -2.090386 -3.979617 -0.584324
mean -0.348398 -0.663270 -0.097387

In [153]:
tsdf.A.agg(['sum', 'mean'])

sum    -2.090386
mean   -0.348398
Name: A, dtype: float64

In [154]:
tsdf.A.agg(['sum', lambda x: x.mean()])

sum        -2.090386
<lambda>   -0.348398
Name: A, dtype: float64

In [156]:
def mymean(x):
    return x.mean()
tsdf.A.agg(['sum', mymean])

sum      -2.090386
mymean   -0.348398
Name: A, dtype: float64

In [157]:
# Aggregating with a dict

tsdf.agg({'A': 'mean', 'B': 'sum'})

A   -0.348398
B   -3.979617
dtype: float64

In [158]:
tsdf.agg({'A': ['mean', 'min'], 'B': 'sum'})

A         B
mean -0.348398       NaN
min  -2.453917       NaN
sum        NaN -3.979617

In [159]:
# Mixed dtypes

mdf = pd.DataFrame({'A': [1, 2, 3],
                    'B': [1., 2., 3.],
                    'C': ['foo', 'bar', 'baz'],
                    'D': pd.date_range('20130101', periods=3)})
mdf.dtypes

A             int64
B           float64
C            object
D    datetime64[ns]
dtype: object

In [160]:
mdf.agg(['min', 'sum'])

A    B          C          D
min  1  1.0        bar 2013-01-01
sum  6  6.0  foobarbaz        NaT

In [162]:
# Custom describe

from functools import partial
q_25 = partial(pd.Series.quantile, q=0.25)
q_25.__name__ = '25%'
q_75 = partial(pd.Series.quantile, q=0.75)
q_75.__name__ = '75%'
tsdf.agg(['count', 'mean', 'std', 'min', q_25, 'median', q_75, 'max'])

A         B         C
count   6.000000  6.000000  6.000000
mean   -0.348398 -0.663270 -0.097387
std     1.318240  0.861724  1.783692
min    -2.453917 -1.487722 -2.325686
25%    -0.983723 -1.407057 -0.815587
median -0.088214 -0.854847 -0.361318
75%     0.586250  0.110661  0.205743
max     1.011114  0.376429  3.036243

In [165]:
# Transform API

tsdf = pd.DataFrame(np.random.randn(10, 3), columns=['A', 'B', 'C'],
                    index=pd.date_range('1/1/2000', periods=10))
tsdf.iloc[3:7] = np.nan
tsdf

A         B         C
2000-01-01 -0.459044 -0.581953 -1.095872
2000-01-02 -0.489243 -1.647972 -0.955792
2000-01-03  0.369019  0.321769 -0.892708
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08 -0.404238  0.589524 -0.867733
2000-01-09  0.902733  0.069675  0.613434
2000-01-10  0.073615  1.181673 -1.146372

In [166]:
tsdf.transform(np.abs)

A         B         C
2000-01-01  0.459044  0.581953  1.095872
2000-01-02  0.489243  1.647972  0.955792
2000-01-03  0.369019  0.321769  0.892708
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.404238  0.589524  0.867733
2000-01-09  0.902733  0.069675  0.613434
2000-01-10  0.073615  1.181673  1.146372

In [167]:
tsdf.transform('abs')

A         B         C
2000-01-01  0.459044  0.581953  1.095872
2000-01-02  0.489243  1.647972  0.955792
2000-01-03  0.369019  0.321769  0.892708
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.404238  0.589524  0.867733
2000-01-09  0.902733  0.069675  0.613434
2000-01-10  0.073615  1.181673  1.146372

In [168]:
tsdf.transform(lambda x: x.abs())

A         B         C
2000-01-01  0.459044  0.581953  1.095872
2000-01-02  0.489243  1.647972  0.955792
2000-01-03  0.369019  0.321769  0.892708
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.404238  0.589524  0.867733
2000-01-09  0.902733  0.069675  0.613434
2000-01-10  0.073615  1.181673  1.146372

In [169]:
np.abs(tsdf)

A         B         C
2000-01-01  0.459044  0.581953  1.095872
2000-01-02  0.489243  1.647972  0.955792
2000-01-03  0.369019  0.321769  0.892708
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.404238  0.589524  0.867733
2000-01-09  0.902733  0.069675  0.613434
2000-01-10  0.073615  1.181673  1.146372

In [171]:
tsdf.A.transform(np.abs)

2000-01-01    0.459044
2000-01-02    0.489243
2000-01-03    0.369019
2000-01-04         NaN
2000-01-05         NaN
2000-01-06         NaN
2000-01-07         NaN
2000-01-08    0.404238
2000-01-09    0.902733
2000-01-10    0.073615
Freq: D, Name: A, dtype: float64

In [172]:
# Transform with multiple functions

tsdf.transform([np.abs, lambda x: x + 1])

A                   B                   C          
            absolute  <lambda>  absolute  <lambda>  absolute  <lambda>
2000-01-01  0.459044  0.540956  0.581953  0.418047  1.095872 -0.095872
2000-01-02  0.489243  0.510757  1.647972 -0.647972  0.955792  0.044208
2000-01-03  0.369019  1.369019  0.321769  1.321769  0.892708  0.107292
2000-01-04       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN       NaN       NaN       NaN
2000-01-08  0.404238  0.595762  0.589524  1.589524  0.867733  0.132267
2000-01-09  0.902733  1.902733  0.069675  1.069675  0.613434  1.613434
2000-01-10  0.073615  1.073615  1.181673  2.181673  1.146372 -0.146372

In [173]:
tsdf.A.transform([np.abs, lambda x: x + 1])

absolute  <lambda>
2000-01-01  0.459044  0.540956
2000-01-02  0.489243  0.510757
2000-01-03  0.369019  1.369019
2000-01-04       NaN       NaN
2000-01-05       NaN       NaN
2000-01-06       NaN       NaN
2000-01-07       NaN       NaN
2000-01-08  0.404238  0.595762
2000-01-09  0.902733  1.902733
2000-01-10  0.073615  1.073615

In [174]:
# Transforming with a dict

tsdf.transform({'A': np.abs, 'B': lambda x: x + 1})

A         B
2000-01-01  0.459044  0.418047
2000-01-02  0.489243 -0.647972
2000-01-03  0.369019  1.321769
2000-01-04       NaN       NaN
2000-01-05       NaN       NaN
2000-01-06       NaN       NaN
2000-01-07       NaN       NaN
2000-01-08  0.404238  1.589524
2000-01-09  0.902733  1.069675
2000-01-10  0.073615  2.181673

In [176]:
tsdf.transform({'A': np.abs, 'B': [lambda x: x + 1, 'sqrt']})

A         B          
            absolute  <lambda>      sqrt
2000-01-01  0.459044  0.418047       NaN
2000-01-02  0.489243 -0.647972       NaN
2000-01-03  0.369019  1.321769  0.567247
2000-01-04       NaN       NaN       NaN
2000-01-05       NaN       NaN       NaN
2000-01-06       NaN       NaN       NaN
2000-01-07       NaN       NaN       NaN
2000-01-08  0.404238  1.589524  0.767805
2000-01-09  0.902733  1.069675  0.263960
2000-01-10  0.073615  2.181673  1.087048

In [182]:
# Applying elementwise functions

df4 = df[:4]
df4

one       two     three
a  0.383948 -0.518727       NaN
b  0.176186 -0.375242  0.590151
c -2.641514  0.494866 -0.479331
d       NaN  2.445402 -0.689410

In [183]:
def f(x):
     return len (str(x))
df4['one'].map(f)

a    19
b    18
c    19
d     3
Name: one, dtype: int64

In [184]:
df4.applymap(f)

one  two  three
a   19   19      3
b   18   19     18
c   19   18     19
d    3   18     19

In [188]:
s = pd.Series(['six', 'seven', 'six', 'seven', 'six'],
                index=['a', 'b', 'c', 'd', 'e'])
t = pd.Series({'six': 6., 'seven': 7.})
s

a      six
b    seven
c      six
d    seven
e      six
dtype: object

In [186]:
s.map(t)

a    6.0
b    7.0
c    6.0
d    7.0
e    6.0
dtype: float64

In [189]:
# Reindexing and altering labels

s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s

a    0.000803
b   -0.118665
c   -0.184771
d   -0.038605
e   -1.207486
dtype: float64

In [190]:
s.reindex(['e', 'b', 'f', 'd'])

e   -1.207486
b   -0.118665
f         NaN
d   -0.038605
dtype: float64

In [191]:
df

one       two     three
a  0.383948 -0.518727       NaN
b  0.176186 -0.375242  0.590151
c -2.641514  0.494866 -0.479331
d       NaN  2.445402 -0.689410

In [192]:
df.reindex(index=['c', 'f', 'b'], columns=['three', 'two', 'one'])

three       two       one
c -0.479331  0.494866 -2.641514
f       NaN       NaN       NaN
b  0.590151 -0.375242  0.176186

In [193]:
df.reindex(['c', 'f', 'b'], axis='index')

one       two     three
c -2.641514  0.494866 -0.479331
f       NaN       NaN       NaN
b  0.176186 -0.375242  0.590151

In [194]:
rs = s.reindex(df.index)
rs

a    0.000803
b   -0.118665
c   -0.184771
d   -0.038605
dtype: float64

In [195]:
rs.index is df.index

True

In [196]:
df.reindex(['c', 'f', 'b'], axis='index')

one       two     three
c -2.641514  0.494866 -0.479331
f       NaN       NaN       NaN
b  0.176186 -0.375242  0.590151

In [197]:
df.reindex(['three', 'two', 'one'], axis='columns')

three       two       one
a       NaN -0.518727  0.383948
b  0.590151 -0.375242  0.176186
c -0.479331  0.494866 -2.641514
d -0.689410  2.445402       NaN

In [201]:
# Reindexing to align with another object

df2

A    B
0  5.0  NaN
1  2.0  NaN
2  4.0  3.0
3  NaN  4.0
4  3.0  6.0
5  7.0  8.0

In [202]:
df3

A
e  2.0
d  1.0
c  1.0
b  3.0
a  NaN

In [203]:
df.reindex_like(df2)

A   B
0 NaN NaN
1 NaN NaN
2 NaN NaN
3 NaN NaN
4 NaN NaN
5 NaN NaN

In [204]:
# Aligning objects with each other with align

s = pd.Series(np.random.randn(5), index=['a', 'b', 'c', 'd', 'e'])
s1 = s[:4]
s2 = s[1:]
s1.align(s2)

(a    1.592793
 b    0.110123
 c    1.201114
 d    0.242080
 e         NaN
 dtype: float64, a         NaN
 b    0.110123
 c    1.201114
 d    0.242080
 e    2.640809
 dtype: float64)

In [205]:
s1.align(s2, join='inner')

(b    0.110123
 c    1.201114
 d    0.242080
 dtype: float64, b    0.110123
 c    1.201114
 d    0.242080
 dtype: float64)

In [206]:
s1.align(s2, join='left')

(a    1.592793
 b    0.110123
 c    1.201114
 d    0.242080
 dtype: float64, a         NaN
 b    0.110123
 c    1.201114
 d    0.242080
 dtype: float64)

In [207]:
df.align(df2, join='inner')

(Empty DataFrame
 Columns: []
 Index: [], Empty DataFrame
 Columns: []
 Index: [])

In [208]:
df.align(df2, join='inner', axis=0)

(Empty DataFrame
 Columns: [one, two, three]
 Index: [], Empty DataFrame
 Columns: [A, B]
 Index: [])

In [209]:
df.align(df2.iloc[0], axis=1)

(    A   B       one     three       two
 a NaN NaN  0.383948       NaN -0.518727
 b NaN NaN  0.176186  0.590151 -0.375242
 c NaN NaN -2.641514 -0.479331  0.494866
 d NaN NaN       NaN -0.689410  2.445402, A        5.0
 B        NaN
 one      NaN
 three    NaN
 two      NaN
 Name: 0, dtype: float64)

In [210]:
# Filling while reindexing

rng = pd.date_range('1/3/2000', periods=8)
ts = pd.Series(np.random.randn(8), index=rng)
ts2 = ts[[0, 3, 6]]
ts

2000-01-03   -0.487054
2000-01-04   -0.270753
2000-01-05    0.191410
2000-01-06    0.637833
2000-01-07   -0.949268
2000-01-08   -0.151706
2000-01-09   -0.396032
2000-01-10    0.824242
Freq: D, dtype: float64

In [211]:
ts2

2000-01-03   -0.487054
2000-01-06    0.637833
2000-01-09   -0.396032
dtype: float64

In [212]:
ts2.reindex(ts.index)

2000-01-03   -0.487054
2000-01-04         NaN
2000-01-05         NaN
2000-01-06    0.637833
2000-01-07         NaN
2000-01-08         NaN
2000-01-09   -0.396032
2000-01-10         NaN
Freq: D, dtype: float64

In [213]:
ts2.reindex(ts.index, method='ffill')

2000-01-03   -0.487054
2000-01-04   -0.487054
2000-01-05   -0.487054
2000-01-06    0.637833
2000-01-07    0.637833
2000-01-08    0.637833
2000-01-09   -0.396032
2000-01-10   -0.396032
Freq: D, dtype: float64

In [214]:
ts2.reindex(ts.index, method='bfill')

2000-01-03   -0.487054
2000-01-04    0.637833
2000-01-05    0.637833
2000-01-06    0.637833
2000-01-07   -0.396032
2000-01-08   -0.396032
2000-01-09   -0.396032
2000-01-10         NaN
Freq: D, dtype: float64

In [215]:
ts2.reindex(ts.index, method='nearest')

2000-01-03   -0.487054
2000-01-04   -0.487054
2000-01-05    0.637833
2000-01-06    0.637833
2000-01-07    0.637833
2000-01-08   -0.396032
2000-01-09   -0.396032
2000-01-10   -0.396032
Freq: D, dtype: float64

In [218]:
ts2.reindex(ts.index).fillna(method='ffill')

2000-01-03   -0.487054
2000-01-04   -0.487054
2000-01-05   -0.487054
2000-01-06    0.637833
2000-01-07    0.637833
2000-01-08    0.637833
2000-01-09   -0.396032
2000-01-10   -0.396032
Freq: D, dtype: float64

In [219]:
# Limits on filling while reindexing

ts2.reindex(ts.index, method='ffill', limit=1)

2000-01-03   -0.487054
2000-01-04   -0.487054
2000-01-05         NaN
2000-01-06    0.637833
2000-01-07    0.637833
2000-01-08         NaN
2000-01-09   -0.396032
2000-01-10   -0.396032
Freq: D, dtype: float64

In [220]:
ts2.reindex(ts.index, method='ffill', tolerance='1 day')

2000-01-03   -0.487054
2000-01-04   -0.487054
2000-01-05         NaN
2000-01-06    0.637833
2000-01-07    0.637833
2000-01-08         NaN
2000-01-09   -0.396032
2000-01-10   -0.396032
Freq: D, dtype: float64

In [221]:
# Dropping labels from an axis

df

one       two     three
a  0.383948 -0.518727       NaN
b  0.176186 -0.375242  0.590151
c -2.641514  0.494866 -0.479331
d       NaN  2.445402 -0.689410

In [222]:
df.drop(['a', 'd'], axis=0)

one       two     three
b  0.176186 -0.375242  0.590151
c -2.641514  0.494866 -0.479331

In [223]:
df.drop(['one'], axis=1)

two     three
a -0.518727       NaN
b -0.375242  0.590151
c  0.494866 -0.479331
d  2.445402 -0.689410

In [224]:
df.reindex(df.index.difference(['a', 'd']))

one       two     three
b  0.176186 -0.375242  0.590151
c -2.641514  0.494866 -0.479331

In [225]:
# Renaming / mapping labels

s

a    1.592793
b    0.110123
c    1.201114
d    0.242080
e    2.640809
dtype: float64

In [226]:
s.rename(str.upper)

A    1.592793
B    0.110123
C    1.201114
D    0.242080
E    2.640809
dtype: float64

In [228]:
df.rename(columns={'one': 'foo', 'two': 'bar'},
            index={'a': 'apple', 'b': 'banana', 'd': 'durian'})

foo       bar     three
apple   0.383948 -0.518727       NaN
banana  0.176186 -0.375242  0.590151
c      -2.641514  0.494866 -0.479331
durian       NaN  2.445402 -0.689410

In [229]:
df.rename({'one': 'foo', 'two': 'bar'}, axis='columns')

foo       bar     three
a  0.383948 -0.518727       NaN
b  0.176186 -0.375242  0.590151
c -2.641514  0.494866 -0.479331
d       NaN  2.445402 -0.689410

In [230]:
df.rename({'a': 'apple', 'b': 'banana', 'd': 'durian'}, axis='index')

one       two     three
apple   0.383948 -0.518727       NaN
banana  0.176186 -0.375242  0.590151
c      -2.641514  0.494866 -0.479331
durian       NaN  2.445402 -0.689410

In [231]:
s.rename("scalar-name")

a    1.592793
b    0.110123
c    1.201114
d    0.242080
e    2.640809
Name: scalar-name, dtype: float64

In [232]:
df = pd.DataFrame({'x': [1, 2, 3, 4, 5, 6],
                    'y': [10, 20, 30, 40, 50, 60]},
                    index=pd.MultiIndex.from_product([['a', 'b', 'c'], [1, 2]],
                    names=['let', 'num']))
df

x   y
let num       
a   1    1  10
    2    2  20
b   1    3  30
    2    4  40
c   1    5  50
    2    6  60

In [233]:
df.rename_axis(index={'let': 'abc'})

x   y
abc num       
a   1    1  10
    2    2  20
b   1    3  30
    2    4  40
c   1    5  50
    2    6  60

In [234]:
df.rename_axis(index=str.upper)

x   y
LET NUM       
a   1    1  10
    2    2  20
b   1    3  30
    2    4  40
c   1    5  50
    2    6  60

In [237]:
# Iteration

df = pd.DataFrame({'col1': np.random.randn(3),
                    'col2': np.random.randn(3)}, index=['a', 'b', 'c'])
for col in df:
    print(col)

col1
col2


In [238]:
df = pd.DataFrame({'a': [1, 2, 3], 'b': ['a', 'b', 'c']})
for index, row in df.iterrows():
    row['a'] = 10
df

a  b
0  1  a
1  2  b
2  3  c

In [239]:
# items

for row_index, row in df.iterrows():
    print(row_index, row, sep='\n')

0
a    1
b    a
Name: 0, dtype: object
1
a    2
b    b
Name: 1, dtype: object
2
a    3
b    c
Name: 2, dtype: object


In [240]:
df_orig = pd.DataFrame([[1, 1.5]], columns=['int', 'float'])
df_orig.dtypes

int        int64
float    float64
dtype: object

In [241]:
row = next(df_orig.iterrows())[1]
row

int      1.0
float    1.5
Name: 0, dtype: float64

In [242]:
row['int'].dtype

dtype('float64')

In [243]:
df_orig['int'].dtype

dtype('int64')

In [244]:
df2 = pd.DataFrame({'x': [1, 2, 3], 'y': [4, 5, 6]})
print(df2)

   x  y
0  1  4
1  2  5
2  3  6


In [245]:
print(df2.T)

   0  1  2
x  1  2  3
y  4  5  6


In [246]:
df2_t = pd.DataFrame({idx: values for idx, values in df2.iterrows()})
print(df2_t)

   0  1  2
x  1  2  3
y  4  5  6


In [247]:
# itertuples

for row in df.itertuples():
    print(row)

Pandas(Index=0, a=1, b='a')
Pandas(Index=1, a=2, b='b')
Pandas(Index=2, a=3, b='c')


In [248]:
#.dt accessor

# datetime
s = pd.Series(pd.date_range('20130101 09:10:12', periods=4))
s

0   2013-01-01 09:10:12
1   2013-01-02 09:10:12
2   2013-01-03 09:10:12
3   2013-01-04 09:10:12
dtype: datetime64[ns]

In [249]:
s.dt.hour

0    9
1    9
2    9
3    9
dtype: int64

In [250]:
s.dt.hour

0    9
1    9
2    9
3    9
dtype: int64

In [251]:
s.dt.second

0    12
1    12
2    12
3    12
dtype: int64

In [252]:
s.dt.day

0    1
1    2
2    3
3    4
dtype: int64

In [253]:
s[s.dt.day == 2]

1   2013-01-02 09:10:12
dtype: datetime64[ns]

In [255]:
stz = s.dt.tz_localize('US/Eastern')
stz

0   2013-01-01 09:10:12-05:00
1   2013-01-02 09:10:12-05:00
2   2013-01-03 09:10:12-05:00
3   2013-01-04 09:10:12-05:00
dtype: datetime64[ns, US/Eastern]

In [256]:
stz.dt.tz

<DstTzInfo 'US/Eastern' LMT-1 day, 19:04:00 STD>

In [257]:
s.dt.tz_localize('UTC').dt.tz_convert('US/Eastern')

0   2013-01-01 04:10:12-05:00
1   2013-01-02 04:10:12-05:00
2   2013-01-03 04:10:12-05:00
3   2013-01-04 04:10:12-05:00
dtype: datetime64[ns, US/Eastern]

In [258]:
# DatetimeIndex
s = pd.Series(pd.date_range('20130101', periods=4))
s

0   2013-01-01
1   2013-01-02
2   2013-01-03
3   2013-01-04
dtype: datetime64[ns]

In [259]:
s.dt.strftime('%Y/%m/%d')

0    2013/01/01
1    2013/01/02
2    2013/01/03
3    2013/01/04
dtype: object

In [260]:
# PeriodIndex
s = pd.Series(pd.period_range('20130101', periods=4))
s

0    2013-01-01
1    2013-01-02
2    2013-01-03
3    2013-01-04
dtype: period[D]

In [261]:
s.dt.strftime('%Y/%m/%d')

0    2013/01/01
1    2013/01/02
2    2013/01/03
3    2013/01/04
dtype: object

In [262]:
# period
s = pd.Series(pd.period_range('20130101', periods=4, freq='D'))
s

0    2013-01-01
1    2013-01-02
2    2013-01-03
3    2013-01-04
dtype: period[D]

In [263]:
s.dt.year

0    2013
1    2013
2    2013
3    2013
dtype: int64

In [264]:
s.dt.day

0    1
1    2
2    3
3    4
dtype: int64

In [265]:
# timedelta
s = pd.Series(pd.timedelta_range('1 day 00:00:05', periods=4, freq='s'))
s

0   1 days 00:00:05
1   1 days 00:00:06
2   1 days 00:00:07
3   1 days 00:00:08
dtype: timedelta64[ns]

In [266]:
s.dt.days

0    1
1    1
2    1
3    1
dtype: int64

In [267]:
s.dt.seconds

0    5
1    6
2    7
3    8
dtype: int64

In [268]:
s.dt.components

days  hours  minutes  seconds  milliseconds  microseconds  nanoseconds
0     1      0        0        5             0             0            0
1     1      0        0        6             0             0            0
2     1      0        0        7             0             0            0
3     1      0        0        8             0             0            0

In [269]:
# Vectorized string methods

s = pd.Series(['A', 'B', 'C', 'Aaba', 'Baca', np.nan, 'CABA', 'dog', 'cat'])
s.str.lower()

0       a
1       b
2       c
3    aaba
4    baca
5     NaN
6    caba
7     dog
8     cat
dtype: object

In [270]:
# Sorting
# By index

df = pd.DataFrame({
    'one': pd.Series(np.random.randn(3), index=['a', 'b', 'c']),
    'two': pd.Series(np.random.randn(4), index=['a', 'b', 'c', 'd']),
    'three': pd.Series(np.random.randn(3), index=['b', 'c', 'd'])})
unsorted_df = df.reindex(index=['a', 'd', 'c', 'b'],
                        columns=['three', 'two', 'one'])
unsorted_df

three       two       one
a       NaN -1.641239  0.281545
d  0.219981 -1.269998       NaN
c  2.017014 -0.615375  1.651949
b -0.892804 -0.188428  1.511155

In [271]:
# DataFrame
unsorted_df.sort_index()

three       two       one
a       NaN -1.641239  0.281545
b -0.892804 -0.188428  1.511155
c  2.017014 -0.615375  1.651949
d  0.219981 -1.269998       NaN

In [272]:
unsorted_df.sort_index(ascending=False)

three       two       one
d  0.219981 -1.269998       NaN
c  2.017014 -0.615375  1.651949
b -0.892804 -0.188428  1.511155
a       NaN -1.641239  0.281545

In [273]:
unsorted_df.sort_index(axis=1)

one     three       two
a  0.281545       NaN -1.641239
d       NaN  0.219981 -1.269998
c  1.651949  2.017014 -0.615375
b  1.511155 -0.892804 -0.188428

In [274]:
# Series
unsorted_df['three'].sort_index()

a         NaN
b   -0.892804
c    2.017014
d    0.219981
Name: three, dtype: float64

In [275]:
# By Values

df1 = pd.DataFrame({'one': [2, 1, 1, 1],
                    'two': [1, 3, 2, 4],
                    'three': [5, 4, 3, 2]})
df1.sort_values(by='two')

one  two  three
0    2    1      5
2    1    2      3
1    1    3      4
3    1    4      2

In [276]:
df1[['one', 'two', 'three']].sort_values(by=['one', 'two'])

one  two  three
2    1    2      3
1    1    3      4
3    1    4      2
0    2    1      5

In [277]:
s[2] = np.nan
s.sort_values()

0       A
3    Aaba
1       B
4    Baca
6    CABA
8     cat
7     dog
2     NaN
5     NaN
dtype: object

In [278]:
s.sort_values(na_position='first')

2     NaN
5     NaN
0       A
3    Aaba
1       B
4    Baca
6    CABA
8     cat
7     dog
dtype: object

In [281]:
# By indexes and values

# Build MultiIndex
idx = pd.MultiIndex.from_tuples([('a', 1), ('a', 2), ('a', 2),
                                            ('b', 2), ('b', 1), ('b', 1)])
idx.names = ['first', 'second']

# Build DataFrame
df_multi = pd.DataFrame({'A': np.arange(6, 0, -1)},
                                    index=idx)
df_multi

A
first second   
a     1       6
      2       5
      2       4
b     2       3
      1       2
      1       1

In [282]:
df_multi.sort_values(by=['second', 'A'])

A
first second   
b     1       1
      1       2
a     1       6
b     2       3
a     2       4
      2       5

In [283]:
# searchsorted

ser = pd.Series([1, 2, 3])
ser.searchsorted([0, 3])

array([0, 2], dtype=int64)

In [284]:
ser.searchsorted([0, 4])

array([0, 3], dtype=int64)

In [285]:
ser.searchsorted([1, 3], side='right')

array([1, 3], dtype=int64)

In [286]:
ser.searchsorted([1, 3], side='left')

array([0, 2], dtype=int64)

In [287]:
ser = pd.Series([3, 1, 2])
ser.searchsorted([0, 3], sorter=np.argsort(ser))

array([0, 2], dtype=int64)

In [288]:
# smallest / largest values

s = pd.Series(np.random.permutation(10))
s

0    6
1    9
2    8
3    0
4    1
5    7
6    2
7    3
8    4
9    5
dtype: int32

In [289]:
s.sort_values()

3    0
4    1
6    2
7    3
8    4
9    5
0    6
5    7
2    8
1    9
dtype: int32

In [290]:
s.nsmallest(3)

3    0
4    1
6    2
dtype: int32

In [291]:
s.nlargest(3)

1    9
2    8
5    7
dtype: int32

In [292]:
df = pd.DataFrame({'a': [-2, -1, 1, 10, 8, 11, -1],
                    'b': list('abdceff'),
                    'c': [1.0, 2.0, 4.0, 3.2, np.nan, 3.0, 4.0]})
df.nlargest(3, 'a')

a  b    c
5  11  f  3.0
3  10  c  3.2
4   8  e  NaN

In [293]:
df.nlargest(5, ['a', 'c'])

a  b    c
5  11  f  3.0
3  10  c  3.2
4   8  e  NaN
2   1  d  4.0
6  -1  f  4.0

In [294]:
df.nsmallest(3, 'a')

a  b    c
0 -2  a  1.0
1 -1  b  2.0
6 -1  f  4.0

In [295]:
df.nsmallest(5, ['a', 'c'])

a  b    c
0 -2  a  1.0
1 -1  b  2.0
6 -1  f  4.0
2  1  d  4.0
4  8  e  NaN

In [296]:
# Sorting by a MultiIndex column

df1.columns = pd.MultiIndex.from_tuples([('a', 'one'),
                                        ('a', 'two'),
                                        ('b', 'three')])
df1.sort_values(by=('a', 'two'))

a         b
  one two three
0   2   1     5
2   1   2     3
1   1   3     4
3   1   4     2

In [297]:
# Copying
# dtypes

dft = pd.DataFrame({'A': np.random.rand(3),
                    'B': 1,
                    'C': 'foo',
                    'D': pd.Timestamp('20010102'),
                    'E': pd.Series([1.0] * 3).astype('float32'),
                    'F': False,
                    'G': pd.Series([1] * 3, dtype='int8')})
dft

A  B    C          D    E      F  G
0  0.572597  1  foo 2001-01-02  1.0  False  1
1  0.536232  1  foo 2001-01-02  1.0  False  1
2  0.711052  1  foo 2001-01-02  1.0  False  1

In [298]:
dft.dtypes

A           float64
B             int64
C            object
D    datetime64[ns]
E           float32
F              bool
G              int8
dtype: object

In [299]:
dft['A'].dtype

dtype('float64')

In [300]:
# these ints are coerced to floats
pd.Series([1, 2, 3, 4, 5, 6.])

0    1.0
1    2.0
2    3.0
3    4.0
4    5.0
5    6.0
dtype: float64

In [301]:
# string data forces an ``object`` dtype
pd.Series([1, 2, 3, 6., 'foo'])

0      1
1      2
2      3
3      6
4    foo
dtype: object

In [302]:
dft.dtypes.value_counts()

bool              1
float32           1
object            1
int64             1
float64           1
int8              1
datetime64[ns]    1
dtype: int64

In [303]:
df1 = pd.DataFrame(np.random.randn(8, 1), columns=['A'], dtype='float32')
df1

A
0  0.613502
1  1.552391
2 -0.260980
3 -0.317549
4 -0.167743
5  2.109415
6 -2.016212
7  0.566523

In [304]:
df1.dtypes

A    float32
dtype: object

In [306]:
df2 = pd.DataFrame({'A': pd.Series(np.random.randn(8), dtype='float16'),
                    'B': pd.Series(np.random.randn(8)),
                    'C': pd.Series(np.array(np.random.randn(8),
                                            dtype='uint8'))})
df2

A         B    C
0 -0.165283 -0.831915    1
1  0.603027 -1.960120    1
2  0.535156  0.794904  255
3  1.842773  0.635309    0
4 -1.673828 -1.295173    0
5 -0.843750 -1.924498    0
6 -0.271484  0.318265    0
7 -0.493164 -0.858420    1

In [307]:
df2.dtypes

A    float16
B    float64
C      uint8
dtype: object

In [308]:
pd.DataFrame([1, 2], columns=['a']).dtypes

a    int64
dtype: object

In [309]:
pd.DataFrame({'a': [1, 2]}).dtypes

a    int64
dtype: object

In [310]:
pd.DataFrame({'a': 1}, index=list(range(2))).dtypes

a    int64
dtype: object

In [311]:
frame = pd.DataFrame(np.array([1, 2]))

In [312]:
# upcasting

df3 = df1.reindex_like(df2).fillna(value=0.0) + df2
df3

A         B      C
0  0.448218 -0.831915    1.0
1  2.155419 -1.960120    1.0
2  0.274176  0.794904  255.0
3  1.525225  0.635309    0.0
4 -1.841571 -1.295173    0.0
5  1.265665 -1.924498    0.0
6 -2.287696  0.318265    0.0
7  0.073359 -0.858420    1.0

In [314]:
df3.dtypes

A    float32
B    float64
C    float64
dtype: object

In [315]:
df3.to_numpy().dtype

dtype('float64')

In [316]:
#astype

df3

A         B      C
0  0.448218 -0.831915    1.0
1  2.155419 -1.960120    1.0
2  0.274176  0.794904  255.0
3  1.525225  0.635309    0.0
4 -1.841571 -1.295173    0.0
5  1.265665 -1.924498    0.0
6 -2.287696  0.318265    0.0
7  0.073359 -0.858420    1.0

In [317]:
df3.dtypes

A    float32
B    float64
C    float64
dtype: object

In [318]:
# conversion of dtypes
df3.astype('float32').dtypes

A    float32
B    float32
C    float32
dtype: object

In [320]:
dft = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
dft[['a', 'b']] = dft[['a', 'b']].astype(np.uint8)
dft

a  b  c
0  1  4  7
1  2  5  8
2  3  6  9

In [321]:
dft.dtypes

a    uint8
b    uint8
c    int64
dtype: object

In [322]:
dft1 = pd.DataFrame({'a': [1, 0, 1], 'b': [4, 5, 6], 'c': [7, 8, 9]})
dft1 = dft1.astype({'a': np.bool, 'c': np.float64})
dft1

a  b    c
0   True  4  7.0
1  False  5  8.0
2   True  6  9.0

In [323]:
dft1.dtypes

a       bool
b      int64
c    float64
dtype: object

In [324]:
dft = pd.DataFrame({'a': [1, 2, 3], 'b': [4, 5, 6], 'c': [7, 8, 9]})
dft.loc[:, ['a', 'b']].astype(np.uint8).dtypes

a    uint8
b    uint8
dtype: object

In [325]:
dft.loc[:, ['a', 'b']] = dft.loc[:, ['a', 'b']].astype(np.uint8)
dft.dtypes

a    int64
b    int64
c    int64
dtype: object

In [326]:
# object conversion

import datetime
df = pd.DataFrame([[1, 2],
                    ['a', 'b'],
                    [datetime.datetime(2016, 3, 2),
                    datetime.datetime(2016, 3, 2)]])
df =df.T
df

0  1                    2
0  1  a  2016-03-02 00:00:00
1  2  b  2016-03-02 00:00:00

In [327]:
df.dtypes

0    object
1    object
2    object
dtype: object

In [328]:
df.infer_objects().dtypes

0             int64
1            object
2    datetime64[ns]
dtype: object

In [329]:
# to_numeric() (conversion to numeric dtypes)

m = ['1.1', 2, 3]
pd.to_numeric(m)

array([1.1, 2. , 3. ])

In [330]:
# to_datetime() (conversion to datetime objects)

import datetime
m = ['2016-07-09', datetime.datetime(2016, 3, 2)]
pd.to_datetime(m)

DatetimeIndex(['2016-07-09', '2016-03-02'], dtype='datetime64[ns]', freq=None)

In [331]:
# to_timedelta() (conversion to timedelta objects)

m = ['5us', pd.Timedelta('1day')]
pd.to_timedelta(m)

TimedeltaIndex(['0 days 00:00:00.000005', '1 days 00:00:00'], dtype='timedelta64[ns]', freq=None)

In [332]:
import datetime
m = ['apple', datetime.datetime(2016, 3, 2)]
pd.to_datetime(m, errors='coerce')

DatetimeIndex(['NaT', '2016-03-02'], dtype='datetime64[ns]', freq=None)

In [333]:
m = ['apple', 2, 3]
pd.to_numeric(m, errors='coerce')

array([nan,  2.,  3.])

In [334]:
m = ['apple', pd.Timedelta('1day')]
pd.to_timedelta(m, errors='coerce')

TimedeltaIndex([NaT, '1 days'], dtype='timedelta64[ns]', freq=None)

In [335]:
import datetime
m = ['apple', datetime.datetime(2016, 3, 2)]
pd.to_datetime(m, errors='ignore')

Index(['apple', 2016-03-02 00:00:00], dtype='object')

In [336]:
m = ['apple', 2, 3]
pd.to_numeric(m, errors='ignore')

array(['apple', 2, 3], dtype=object)

In [337]:
m = ['apple', pd.Timedelta('1day')]
pd.to_timedelta(m, errors='ignore')

array(['apple', Timedelta('1 days 00:00:00')], dtype=object)

In [338]:
m = ['1', 2, 3]
pd.to_numeric(m, downcast='integer')   # smallest signed int dtype

array([1, 2, 3], dtype=int8)

In [339]:
pd.to_numeric(m, downcast='signed')    # same as 'integer'

array([1, 2, 3], dtype=int8)

In [340]:
pd.to_numeric(m, downcast='unsigned')  # smallest unsigned int dtype

array([1, 2, 3], dtype=uint8)

In [341]:
pd.to_numeric(m, downcast='float')     # smallest float dtype

array([1., 2., 3.], dtype=float32)

In [342]:
import datetime
df = pd.DataFrame([
    ['2016-07-09', datetime.datetime(2016, 3, 2)]] * 2, dtype='O')
df

0                    1
0  2016-07-09  2016-03-02 00:00:00
1  2016-07-09  2016-03-02 00:00:00

In [343]:
df.apply(pd.to_datetime)

0          1
0 2016-07-09 2016-03-02
1 2016-07-09 2016-03-02

In [344]:
df = pd.DataFrame([['1.1', 2, 3]] * 2, dtype='O')
df

0  1  2
0  1.1  2  3
1  1.1  2  3

In [345]:
df.apply(pd.to_numeric)

0  1  2
0  1.1  2  3
1  1.1  2  3

In [346]:
df = pd.DataFrame([['5us', pd.Timedelta('1day')]] * 2, dtype='O')
df

0                1
0  5us  1 days 00:00:00
1  5us  1 days 00:00:00

In [347]:
df.apply(pd.to_timedelta)

0      1
0 00:00:00.000005 1 days
1 00:00:00.000005 1 days

In [348]:
# gotchas

dfi = df3.astype('int32')
dfi['E'] = 1
dfi

A  B    C  E
0  0  0    1  1
1  2 -1    1  1
2  0  0  255  1
3  1  0    0  1
4 -1 -1    0  1
5  1 -1    0  1
6 -2  0    0  1
7  0  0    1  1

In [349]:
dfi.dtypes

A    int32
B    int32
C    int32
E    int64
dtype: object

In [350]:
casted = dfi[dfi > 0]
casted

A   B      C  E
0  NaN NaN    1.0  1
1  2.0 NaN    1.0  1
2  NaN NaN  255.0  1
3  1.0 NaN    NaN  1
4  NaN NaN    NaN  1
5  1.0 NaN    NaN  1
6  NaN NaN    NaN  1
7  NaN NaN    1.0  1

In [351]:
casted.dtypes

A    float64
B    float64
C    float64
E      int64
dtype: object

In [352]:
dfa = df3.copy()
dfa['A'] = dfa['A'].astype('float32')
dfa.dtypes

A    float32
B    float64
C    float64
dtype: object

In [353]:
casted = dfa[df2 > 0]
casted

A         B      C
0       NaN       NaN    1.0
1  2.155419       NaN    1.0
2  0.274176  0.794904  255.0
3  1.525225  0.635309    NaN
4       NaN       NaN    NaN
5       NaN       NaN    NaN
6       NaN  0.318265    NaN
7       NaN       NaN    1.0

In [354]:
casted.dtypes

A    float32
B    float64
C    float64
dtype: object

In [355]:
# Selecting columns based on dtype

df = pd.DataFrame({'string': list('abc'),
                    'int64': list(range(1, 4)),
                    'uint8': np.arange(3, 6).astype('u1'),
                    'float64': np.arange(4.0, 7.0),
                    'bool1': [True, False, True],
                    'bool2': [False, True, False],
                    'dates': pd.date_range('now', periods=3),
                    'category': pd.Series(list("ABC")).astype('category')})

df['tdeltas'] = df.dates.diff()
df['uint64'] = np.arange(3, 6).astype('u8')
df['other_dates'] = pd.date_range('20130101', periods=3)
df['tz_aware_dates'] = pd.date_range('20130101', periods=3, tz='US/Eastern')
df

string  int64  uint8  float64  bool1  bool2                      dates  \
0      a      1      3      4.0   True  False 2019-12-07 00:21:42.642550   
1      b      2      4      5.0  False   True 2019-12-08 00:21:42.642550   
2      c      3      5      6.0   True  False 2019-12-09 00:21:42.642550   

  category tdeltas  uint64 other_dates            tz_aware_dates  
0        A     NaT       3  2013-01-01 2013-01-01 00:00:00-05:00  
1        B  1 days       4  2013-01-02 2013-01-02 00:00:00-05:00  
2        C  1 days       5  2013-01-03 2013-01-03 00:00:00-05:00

In [356]:
df.dtypes

string                                object
int64                                  int64
uint8                                  uint8
float64                              float64
bool1                                   bool
bool2                                   bool
dates                         datetime64[ns]
category                            category
tdeltas                      timedelta64[ns]
uint64                                uint64
other_dates                   datetime64[ns]
tz_aware_dates    datetime64[ns, US/Eastern]
dtype: object

In [357]:
df.select_dtypes(include=[bool])

bool1  bool2
0   True  False
1  False   True
2   True  False

In [358]:
df.select_dtypes(include=['bool'])

bool1  bool2
0   True  False
1  False   True
2   True  False

In [359]:
df.select_dtypes(include=['number', 'bool'], exclude=['unsignedinteger'])

int64  float64  bool1  bool2 tdeltas
0      1      4.0   True  False     NaT
1      2      5.0  False   True  1 days
2      3      6.0   True  False  1 days

In [360]:
df.select_dtypes(include=['object'])

string
0      a
1      b
2      c

In [362]:
def subdtypes(dtype):
    subs = dtype.__subclasses__()
    if not subs:
        return dtype
    return [dtype, [subdtypes(dt) for dt in subs]]
subdtypes

<function __main__.subdtypes(dtype)>

In [363]:
subdtypes(np.generic)

[numpy.generic,
 [[numpy.number,
   [[numpy.integer,
     [[numpy.signedinteger,
       [numpy.int8,
        numpy.int16,
        numpy.int32,
        numpy.int32,
        numpy.int64,
        numpy.timedelta64]],
      [numpy.unsignedinteger,
       [numpy.uint8,
        numpy.uint16,
        numpy.uint32,
        numpy.uint32,
        numpy.uint64]]]],
    [numpy.inexact,
     [[numpy.floating,
       [numpy.float16, numpy.float32, numpy.float64, numpy.float64]],
      [numpy.complexfloating,
       [numpy.complex64, numpy.complex128, numpy.complex128]]]]]],
  [numpy.flexible,
   [[numpy.character, [numpy.bytes_, numpy.str_]],
    [numpy.void, [numpy.record]]]],
  numpy.bool_,
  numpy.datetime64,
  numpy.object_]]