In [1]:
# https://www.datacamp.com/community/tutorials/data-structures-python
# Python Data Structures Tutorial

# Integer and Float operations
# Floats
x = 4.0
y = 2.0

# Addition
print(x + y)

# Subtraction
print(x - y)

# Multiplication
print(x * y)

# Returns the quotient
print(x / y)

# Returns the remainder
print(x % y) 

# Absolute value
print(abs(x))

# x to the power y
print(x ** y)

6.0
2.0
8.0
2.0
0.0
4.0
16.0


In [2]:
# String

x = 'Cake'
y = 'Cookie'
x + ' & ' + y

'Cake & Cookie'

In [3]:
# Repeat
x * 2

'CakeCake'

In [4]:
# Range Slicing
z1 = x[2:] 

print(z1)

# Slicing
z2 = y[0] + y[1] 

print(z2)

ke
Co


In [1]:
x = '4'
y = '2'

x + y

'42'

In [2]:
#Capitalize strings

str.capitalize('cookie')

'Cookie'

In [3]:
str1 = "Cake 4 U"
str2 = "404"
len(str1)

8

In [4]:
str1.isdigit()


False

In [5]:
str2.isdigit()


True

In [6]:
str1.replace('4 U', str2)


'Cake 404'

In [7]:
str1 = 'cookie'
str2 = 'cook'
str1.find(str2)

0

In [8]:
str1 = 'I got you a cookie'
str2 = 'cook'
str1.find(str2)

12

In [9]:
# Boolean

x = 4
y = 2
x == y

False

In [10]:
x > y

True

In [11]:
x = 4
y = 2
z = (x==y) # Comparison expression (Evaluates to false)
if z: # Conditional on truth/false value of 'z'
    print("Cookie")
else: print("No Cookie")

No Cookie


In [12]:
# Data Type Conversion

i = 4.0
type(i)

float

In [13]:
# Implicit Data Type Conversion

# A float
x = 4.0 

# An integer
y = 2 

# Divide `x` by `y`
z = x/y

# Check the type of `z`
type(z)

float

In [14]:
# Explicit Data Type Conversion

x = 2
y = "The Godfather: Part "
fav_movie = y + x

TypeError: can only concatenate str (not "int") to str

In [15]:
x = 2
y = "The Godfather: Part "
fav_movie = (y) + str(x)
print(fav_movie)

The Godfather: Part 2


In [16]:
# Non-Primitive Data Structures

import array as arr
a = arr.array("I",[3,6,9])
type(a)

array.array

In [17]:
# List

x = [] # Empty list
type(x)

list

In [18]:
x1 = [1,2,3]
type(x1)

list

In [19]:
x2 = list([1,'apple',3])
type(x2)

list

In [20]:
print(x2[1])

apple


In [21]:
x2[1] = 'orange'
print(x2)

[1, 'orange', 3]


In [22]:
list_num = [1,2,45,6,7,2,90,23,435]
list_char = ['c','o','o','k','i','e']

list_num.append(11) # Add 11 to the list, by default adds to the last position
print(list_num)

[1, 2, 45, 6, 7, 2, 90, 23, 435, 11]


In [23]:
list_num.insert(0, 11)
print(list_num)

[11, 1, 2, 45, 6, 7, 2, 90, 23, 435, 11]


In [24]:
list_char.remove('o') 
print(list_char)

['c', 'o', 'k', 'i', 'e']


In [25]:
list_char.pop(-2) # Removes the item at the specified position
print(list_char)

['c', 'o', 'k', 'e']


In [26]:
list_num.sort() # In-place sorting
print(list_num)

[1, 2, 2, 6, 7, 11, 11, 23, 45, 90, 435]


In [27]:
list.reverse(list_num)
print(list_num)

[435, 90, 45, 23, 11, 11, 7, 6, 2, 2, 1]


In [32]:
# Arrays versus Lists

array_char = array.array("u",["c","a","t","s"])
array_char.tostring()
print(array_char)

NameError: name 'array' is not defined

In [33]:
import numpy as np

arr_a = np.array([3, 6, 9])
arr_b = arr_a/3 # Performing vectorized (element-wise) operations 
print(arr_b)

[1. 2. 3.]


In [34]:
arr_ones = np.ones(4)
print(arr_ones)

[1. 1. 1. 1.]


In [35]:
multi_arr_ones = np.ones((3,4)) # Creating 2D array with 3 rows and 4 columns
print(multi_arr_ones)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [36]:
# Stacks

# Bottom -> 1 -> 2 -> 3 -> 4 -> 5 (Top)
stack = [1,2,3,4,5] 
stack.append(6) # Bottom -> 1 -> 2 -> 3 -> 4 -> 5 -> 6 (Top)
print(stack)

[1, 2, 3, 4, 5, 6]


In [37]:
stack.pop() # Bottom -> 1 -> 2 -> 3 -> 4 -> 5 (Top)
stack.pop() # Bottom -> 1 -> 2 -> 3 -> 4 (Top)
print(stack)

[1, 2, 3, 4]


In [39]:
# Graph

graph = { "a" : ["c", "d"],
          "b" : ["d", "e"],
          "c" : ["a", "e"],
          "d" : ["a", "b"],
          "e" : ["b", "c"]
        }

def define_edges(graph):
    edges = []
    for vertices in graph:
        for neighbour in graph[vertices]:
            edges.append((vertices, neighbour))
    return edges

print(define_edges(graph))

[('a', 'c'), ('a', 'd'), ('b', 'd'), ('b', 'e'), ('c', 'a'), ('c', 'e'), ('d', 'a'), ('d', 'b'), ('e', 'b'), ('e', 'c')]


In [40]:
# Trees

class Tree:
    def __init__(self, info, left=None, right=None):
        self.info = info
        self.left  = left
        self.right = right

    def __str__(self):
        return (str(self.info) + ', Left child: ' + str(self.left) + ', Right child: ' + str(self.right))

tree = Tree(1, Tree(2, 2.1, 2.2), Tree(3, 3.1))
print(tree)

1, Left child: 2, Left child: 2.1, Right child: 2.2, Right child: 3, Left child: 3.1, Right child: None


In [41]:
# Tuples

x_tuple = 1,2,3,4,5
y_tuple = ('c','a','k','e')
x_tuple[0]

1

In [42]:
y_tuple[3]
x_tuple[0] = 0 # Cannot change values inside a tuple

TypeError: 'tuple' object does not support item assignment

In [43]:
# Dictionary

x_dict = {'Edward':1, 'Jorge':2, 'Prem':3, 'Joe':4}
del x_dict['Joe']
x_dict

{'Edward': 1, 'Jorge': 2, 'Prem': 3}

In [44]:
x_dict['Edward'] # Prints the value stored with the key 'Edward'.

1

In [45]:
len(x_dict)

3

In [46]:
x_dict.keys()

dict_keys(['Edward', 'Jorge', 'Prem'])

In [47]:
x_dict.values()

dict_values([1, 2, 3])

In [48]:
# Sets

x_set = set('CAKE&COKE')
y_set = set('COOKIE')

print(x_set)

{'A', 'K', 'O', 'E', 'C', '&'}


In [49]:
print(y_set) # Single unique 'o'

{'I', 'K', 'O', 'C', 'E'}


In [50]:
print(x - y) # All the elements in x_set but not in y_set

TypeError: unsupported operand type(s) for -: 'list' and 'str'

In [51]:
print(x_set|y_set) # Unique elements in x_set or y_set or both

{'A', 'I', 'K', 'O', 'E', 'C', '&'}


In [52]:
print(x_set & y_set) # Elements in both x_set and y_set

{'O', 'E', 'C', 'K'}


In [53]:
# files

# File modes (2nd argument): 'r'(read), 'w'(write), 'a'(appending), 'r+'(both reading and writing)
f = open('file_name', 'w')

# Reads entire file
f.read() 

# Reads one line at a time
f.readline() 

# Writes the string to the file, returning the number of char written
f.write('Add this line.') 

f.close()

UnsupportedOperation: not readable