In [1]:
# Numpy Exercises

# Exercise 1

import numpy as np
np.random.seed(21) # This guarantees the code will generate the same set of random numbers whenever executed
random_integers = np.random.randint(1,high=500000, size=(20, 5))
random_integers

array([[ 80842, 333008, 202553, 140037,  81969],
       [ 63857,  42105, 261540, 481981, 176739],
       [489984, 326386, 110795, 394863,  25024],
       [ 38317,  49982, 408830, 485118,  16119],
       [407675, 231729, 265455, 109413, 103399],
       [174677, 343356, 301717, 224120, 401101],
       [140473, 254634, 112262,  25063, 108262],
       [375059, 406983, 208947, 115641, 296685],
       [444899, 129585, 171318, 313094, 425041],
       [188411, 335140, 141681,  59641, 211420],
       [287650,   8973, 477425, 382803, 465168],
       [  3975,  32213, 160603, 275485, 388234],
       [246225,  56174, 244097,   9350, 496966],
       [225516, 273338,  73335, 283013, 212813],
       [ 38175, 282399, 318413, 337639, 379802],
       [198049, 101115, 419547, 260219, 325793],
       [148593, 425024, 348570, 117968, 107007],
       [ 52547, 180346, 178760, 305186, 262153],
       [ 11835, 449971, 494184, 472031, 353049],
       [476442,  35455, 191553, 384154,  29917]])

In [ ]:
# Exercise 2



In [ ]:
# Exercise 3



In [2]:
# Exercise 4

import numpy as np
first_matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(first_matrix)

[[1 2 3]
 [4 5 6]]


In [3]:
second_matrix = np.array([1, 2, 3])
print(second_matrix)

[1 2 3]


In [4]:
first_matrix + second_matrix

array([[2, 4, 6],
       [5, 7, 9]])

In [5]:
# Exercise 5

my_vector = np.array([1, 2, 3, 4, 5, 6])
selection = my_vector % 2 == 0
my_vector[selection]

array([2, 4, 6])

In [6]:
# Exercise 6

import numpy as np
my_array = np.array([1, 2, 3, 4])
my_array

array([1, 2, 3, 4])

In [7]:
my_slice = my_array[1:3]
my_slice

array([2, 3])

In [8]:
my_slice[0] = -1
my_slice

array([-1,  3])

In [9]:
my_array

array([ 1, -1,  3,  4])

In [10]:
my_array[1]

-1

In [11]:
x = [1, 2, 3]
y = x[0:2]
y[0] = "a change"
y

['a change', 2]

In [12]:
x

[1, 2, 3]

In [13]:
my_array = np.array([1, 2, 3])
my_slice = my_array[1:3]
my_slice[0] = -1
my_array

array([ 1, -1,  3])

In [14]:
my_array = np.array([1, 2, 3])
my_slice = my_array[[1,2]]
my_slice[0] = -1
my_array

array([1, 2, 3])

In [15]:
my_array = np.array([1, 2, 3])
my_slice = my_array[1:3]
my_slice = my_slice * 2
my_slice

array([4, 6])

In [16]:
my_array

array([1, 2, 3])

In [17]:
my_array = np.array([1, 2, 3])
my_slice = my_array[1:3]
my_slice[:] = my_slice * 2
my_slice

array([4, 6])

In [18]:
my_array

array([1, 4, 6])

In [21]:
# Exercise 7

my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)
my_slice = my_array[:, 1:3]

[[1 2 3]
 [4 5 6]]


In [23]:
# Exercise 8

my_array[:, :] = my_array * 2
my_slice

array([[ 8, 12],
       [20, 24]])

In [26]:
# Exercise 9

my_array = my_array * 2
my_slice

array([[ 8, 12],
       [20, 24]])

In [27]:
# Exercise 10

# Exercise 11

my_array = np.array([[1, 2, 3], [4, 5, 6]])
print(my_array)

[[1 2 3]
 [4 5 6]]


In [28]:
my_slice = my_array[:, 1:3].copy()
print(my_slice)

[[2 3]
 [5 6]]


In [29]:
my_array[:, :] = my_array * 2
my_slice

array([[2, 3],
       [5, 6]])

In [30]:
my_slice.base is my_array

False

In [31]:
my_array = np.array([1, 2, 3])
my_slice = my_array[1:3]
my_slice.base is my_array

True

In [32]:
my_array = np.array([1, 2, 3])
my_array = my_array[1:4]
my_slice = my_array[1:3]
my_slice.base is my_array

False

In [33]:
my_slice

array([3])

In [34]:
my_array

array([2, 3])

In [35]:
# But a change to `my_slice` still impacts `my_array`.
my_slice[0] = -1
my_array

array([ 2, -1])

In [36]:
my_slice.base is my_array.base

True

SyntaxError: invalid syntax (<ipython-input-37-9b79fc9bed1c>, line 1)